### ISSUE TITLE
Pressure map

### ISSUE THREAD

**Issue by ndhuygelaere** [OIEau/uwwtd#109]
use EPRT for define range of different pressure.

Use also colors 
Add understable label for legend (not the same foreach items)

**Comment by friboben** [comment]
threshold for PRTR is 50t/y for Ntot, 5t/y for Ptot and 50t/y for TOC. As the regulation says TOC or COD/3, we can consider thershold for COD 150t/y. Instead of 3 classes, we could have 2 classes: below PRTR threshold with yellow colour and above PRTR threshold with red colour for N, P and COD. We may, by extension, define a threshold for BOD. As in domestic wastewater generally the relationship between BOD and COD is 2/3 of BOD, we could use a threshold of 1.67 x COD = 225t BOD/y.

**Comment by Rakedjian** [comment]
It is better to have two thresholds than one in order to have three different classes.
The EPRTRT could be one of the thresholds and for each parameter you have to find one that is sufficiently representative. 
The ideal situation is to have a threshold related to emissions from UWWTPs of more than 100 000 p;e.

The second threshold could be closes to the emissions from UWWTPS of more than 10 000 p.e.

There is also a need to have a threshold close to a number easy to read such as 10, 20, 25, 50, 100, 150. 
For phosphorus if the first threshold is 5t/y, the second could be 1t/y
For nitrogen 50 and 10
For COD 150 and 30

as regards BOD it seems strange that it is more than COD. There is an inversion.  100 t/y is certainly more appropriate.
For BOD: 100 and 20

**Comment by friboben** [comment]
As the PRTR is meant to cover agglomerations of more than 100.000pe, I suggest we use the PRTR one and a second threshold 10 times lower:
BOD: 100 and 10
COD 150 and 15
N: 50 and 5
P: 5 and 0.5

**Comment by Rakedjian** [comment]
The threshold adopted for UWWTP has to be the same than the threshold adopted for EPRTR if we put them on the same map.

It is ok. Normally if we divide by ten it means that it represent the pressure related to 10 000 p.e. UWWTPs

**Comment by friboben** [comment]
This is done on all platforms with the colours but of course mainly visible on PL, SI or LT, see for instance http://webnuxdev.rnde.tm.fr/uwwtd_lt/uwwtps/pressure

**Comment by ndhuygelaere** [comment]
done
