### ISSUE TITLE
Summary legal compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#124]
Problème dans le tableau irlandais au niveau de la feuille summary legal compliance

IL y a un léger problème de calcul dans les excemptions au niveau de l'article 5. Si on additionne 439 729 et 842 993 on obtient 1 282 722 et non 1294 722. le pb se situe t'il avec les agglos à 10 000 juste ? Dans le register fait pour le dernier reporting on a 451 729 au lieu de 439 729

![registersummary legal compliance](https://cloud.githubusercontent.com/assets/16286544/12322711/1c8c0f7c-bab6-11e5-91d8-0c9a6cfaf46a.PNG)

**Comment by bbondier** [comment]
Has been fixed, condition was > 2000 and < 10000

**Comment by Rakedjian** [comment]
It is >= 2000 and < 10000

**Comment by friboben** [comment]
Sorry for unclarity, what was meant is that condition > 2000 and < 10000 was false, generating differences in results. Please note with correction >= 2000 and =< 10000 implemented, the result is exactly the same as the 2012 register and therefore the issue is considered fixed. In fact there was a difference of 12000pe and this was due to existence of one agglomeration of exactly 2000pe and one of exactly 10000pe.

**Comment by Rakedjian** [comment]
You are right This is >= 2000 and >= 10 000
