### ISSUE TITLE
Compliance approach

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#150]
It is impossible to have a compliance Article 4 or Article 5 when Article 3 is not compliant.

There is still a problem in these agglomerations
http://uwwtd.oieau.fr/slovenia/agglomeration/si20002/2012
http://uwwtd.oieau.fr/slovenia/agglomeration/si20570/2012
http://uwwtd.oieau.fr/slovenia/agglomeration/si04115/2012
http://uwwtd.oieau.fr/slovenia/agglomeration/si05628/2012
http://uwwtd.oieau.fr/slovenia/agglomeration/si01867/2012

It means that there is still a problem with the compliance algorithm

**Comment by friboben** [comment]
In the past and with the algorithms, you wanted to have individual compliance by article, ie the treatment plant is effectively treating 2ndary, even if the collection was not compliant, and it is how the algorithms work. This allows showing the distance to compliance of each part of the collection and treatment system. If we change this now, this will have an impact on many parts: calculation of distance to compliance, calculation of register... I do not see it technically feasible now. In addition, it will hide all situations where the treatment plant is working well. The overall compliance is taking into account the ascending non compliance, and the individual compliance by article is also considered in the register. Maybe an additional explanation is needed somewhere to detail the approach in the fiche, but the algorithms are already very detailed and avaialble as pdf. Please advise.

**Comment by Rakedjian** [comment]
Attention c''est un sujet très sensible et j'ai déjà signalé ce fait de nombreuses fois au niveau de la conformité agglomération. Le calcul de la conformité légale n'est pas négociable. C'est un principe en chaine et c'est le fondement du site. Si Article 3 est non conforme alors Article 4 et 5 non conforme. Je ne sais pas ce qui s'est passé et pourquoi les derniers algorithmes reviennent sur ce point.

**Comment by friboben** [comment]
It is not a change in the algorithms, there is no modification of the hierarchical compliance at all since the beginning. What you call legal compliance is calculated as the agglomeration compliance: first line in the agglomeration fiche and value used for the timeline. The rest is the compliance by article that is used for the distance to compliance calculation in the register, in the section distance to compliance of the part view stat and in the agglomeration fiches. As detailed in a separate e-mail, considering the hierarchical compliance for each article on the fiche may create confusion for a non expert, but as you consider it a must, we will modify according to your request.
**To solve this now we propose the following: ** when the 2nd treatment is compliant (3rd treatment respectively) and the connection is not compliant (2nd treatment respectively), we change the 2nd treatment compliance to "not compliant*" (respectively 3rd treatment where relevant) and we put "*due to hierarchical compliance" at bottom of box. **Please confirm this is OK for you.**
Should you want to have a modification in the register to add for the distance to compliance a line for 2nd and 3rd "due to hierarchical compliance", this means a bigger work to change the register and the graphs, and would have to be included in the next service request.

**Comment by friboben** [comment]
OK to adjust agglomeration fiches as detailed above as discussed over the phone. Need also to update agglomeration summaryt page like here http://uwwtd.oieau.fr/slovenia/agglomerations/compliance to have in the table 2nd treatment compliance and 3rd treatment compliance respectively corrected to not compliant when connection compliance is not compliant or 2nd treatment compliance is not compliant (hierarchical compliance)

**Comment by ndhuygelaere** [comment]
fixed on devel website.
We change the display value on agglomeration fiche and agglomeration summary page
