### ISSUE TITLE
Compliance graphs in the Viewstats

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#152]
Is the last title "distance to compliance or "compliance"

It seems that the graphs are more related to the legal compliance

![compliancegraph](https://cloud.githubusercontent.com/assets/16286544/12890107/7df9867e-ce82-11e5-91fc-583a8b9d7b32.PNG)

Delete 4 in the following title

"Secondary treatment compliance 4 by number of agglomerations"

**Comment by ndhuygelaere** [comment]
Title are updated

**Comment by friboben** [comment]
here it is only the distance to compliance by article as calculated in the register. It is a very useful information for a non expert as for instance a politician. He/she can then understand where the problem lies: is it the collection, is it the main treatment, is it the more stringent treatment. In the future we could refine this by showing separately the question of performance and of equipment, and also by showing the "legal compliance"

**Comment by Rakedjian** [comment]
Ok but where are the graphs related to the legal compliance under Article 3, 4 and 5

**Comment by friboben** [comment]
After checking, this is effectively the graphs on legal compliance from the register, we have to change the titles to reflect better the content. I propose to call the section Summary legal compliance and to call the individual graphs "legal compliance for connection/2nd treatment/3rd treatment in p.e." & "legal compliance for connection/2nd treatment/3rd treatment by number of agglomeration" respectively.

**Comment by Rakedjian** [comment]
perfect

**Comment by vincentgode** [comment]
Titles updated
