### ISSUE TITLE
REGISTER SI AGGLO MARIBOR_29

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#167]
We have an issue with the compliance because it is written that the total load is compliant but after that we have a NC under Article 4. in this case this is due to the small UWWTP that belongs to the agglomeration and the problem of the Agglo/UWWTP table. There is an approximation in this table that has as consequences the lack of addition of the load entering the small UWWTP. The small UWWTP is not compliant and creates a none compliance of the agglomeration but don't see it as regards the load connected. This problem is more related to the coherence of the information in the reporting than a problem of algorithms. No need to change anything at this stage but these situations will perhaps have to be managed differently during the reporting

http://webnuxdev.rnde.tm.fr/uwwtd_si/agglomeration/si00029/2012

![register agglo maribor_29](https://cloud.githubusercontent.com/assets/16286544/13012079/05e29ace-d1aa-11e5-8bb5-305e7ee0be2f.PNG)

**Comment by friboben** [comment]
In this case, what lands in column compliant is the load entering Maribor treatment plant, (which is here equal to load in collective system) but the load entering the small treatment plant being set at 0% in table uwwagglo, the NC load is set at 0 (see synoptic). What is not clear here is that as the load entering Maribor treatment plant = load in collective system, it may be that the small TP was disconnected but is still reported. The consequence is that it creates a NC situation but it is due to the data, not to the algorithm calculations. This is again a good demonstration that the platform allows identify strange situations and hence improve the dataset.
