### ISSUE TITLE
Romania SIIF website Pb of algorithm

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#182]
We still have a problem of algorithm. Remark already made. 

This situation is not possible 

http://uwwtd.oieau.fr/romania/agglomeration/roag_63759/2012

If the connection is not relevant it means that Article 4 and 5 are not relevant

The deadlines are in 2015. All has to be not relevant

![ro nc nr](https://cloud.githubusercontent.com/assets/16286544/13146149/9fe54334-d654-11e5-9a26-7ba0b85b6551.PNG)

Moreover as regards the UWWTPs related to the agglomerations, the performance are ok but the treatment are not compliant. How is it possible to have zero as regards distance to compliance treatment?

**Comment by bbondier** [comment]
The problem was situated in the implementation of the algorithm. A condition was missing regarding the deadlines of article 4 and 5. We patched this issue and we're launching new calculations tonight. We will get more infos tomorrow once the process is over.
As of the 0% in Distance to compliance table, we're currently investigating this issue.

**Comment by friboben** [comment]
Settled with new calculation, see http://webnuxdev.rnde.tm.fr/uwwtd_ro/agglomeration/roag_63759/2012, has only to be transferred to production platform.

**Comment by Rakedjian** [comment]
Why is the article 5 performance in grey and not blue?
![perf articl 5](https://cloud.githubusercontent.com/assets/16286544/13491567/5208d8e4-e133-11e5-92cd-a1750d331e6e.PNG)
 All the performance are correct.

**Comment by friboben** [comment]
For the visualisation of distance to compliance we have to be coherent with legal compliance. In case the treatment required entails "more stringent other", as the legal compliance does not require the performance to be reported for "more stringent other", the table considers the performance is not assessed and the cell is grey. There is however a mistake here because if combined with N and/or P these last prevail. Corrected in algo, will be transferred with update.

**Comment by Rakedjian** [comment]
OK

I hope that in the future we will have less other and clearer treatments
