### ISSUE TITLE
Concentration graph

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#193]
http://uwwtd.oieau.fr/slovenia/stats/graphs

Is there not a problem of concentration in the Slovenia and Lithuania in the statistic webpage with the concentration graph

![concentration graph](https://cloud.githubusercontent.com/assets/16286544/13286902/6007764c-db04-11e5-924c-1e771d1b56aa.PNG)

**Comment by friboben** [comment]
agreed, problem of units, is correct in UWWTP, hence should be the same here, will be corrected

**Comment by ndhuygelaere** [comment]
For Lithuania, some uwwtp don't have information for N/P/COD/BOD (so this uwwtp count 0 for the missing parameter), but we have volume of waste water  ==> so the national concentration is under-evaluated.
In order to fix this issue, we can  : 
- exclude the corresponding volume for the current parametre. But, it lead to have one national volume of waste water per parameter
- exclude all informations on the uwwtp if one of N, P, COD and BOD is missing ==> it lead to an under-evaluation for N, P, COD and BOD production on the MS Level
- do nothing on the calculation and alert user on the lake of some information

For Poland there are an error on Waste water treated (m3/y) (it need to apply x1000 factor)

**Comment by Rakedjian** [comment]
It has to be well reported by MS. I think that we don't have to change anything and display what is reported and perhaps give only an alert about the inconsistency. 

MS will have to correct their database. 

Best regards
