### ISSUE TITLE
Bulgaria compliance

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#241]
In 2012 this agglomeration was declared compliance. It is not possible because it the same picture the secondary treatment is not compliant. It is under pending deadline but if Article 3 is Ok and Article 4 is not ok it is not possible to have global compliance Ok. It has to be considered as not relevant. 

http://webnuxdev.rnde.tm.fr/uwwtd_bg/agglomeration/bgag6963300/2012

**Comment by friboben** [comment]
In 2012, the agglomeration is compliant to the rule that is valid at this date: collection is at correct level. In 2012 the MS has not to comply to secondary, art4 does not apply in 2012, and is therefore not looked at, this is fully in compliance with the set of algorithms. In addition I find it fair because it recognises the country is respecting what was imposed by the law. In addition the sheet is very clear, there is a large effort remaining to reach requirement for the next deadline, and it is identified in distance to compliance table that will also appear in country report.
If you require us to do this, it means we can not launch the country reports because we have first to again correct the algorithms, launch again compliance calculation for 8th reporting, for 9th reporting, register calculation for both and for each country.

**Comment by Rakedjian** [comment]
I don't undestand this remark.
An agglomeration has to be displayed as compliant only if the calculation shows that it already meets the requirements of the directive no matter the deadline. How can we consider a connection to  a collecting system without correct treatment as a compliant situation.

**Comment by cnassar** [comment]
problem fixed in the algorithme. Need to import the XML file
