### ISSUE TITLE
Compliance calculation and register generation for inactive agglomerations and WWTP

### ISSUE THREAD

**Issue by cnassar** [OIEau/uwwtd#253]
For Luxemburg, 3 agglomerations and 1 WWTP are inactive. However they appear in the register analysis, and the compliance of the WWTP is calculated on the SIIF platform (NC). The inactive WWTP or Agglomerations must be excluded from the compliance calculation and the global analysis.
Agglomeration : http://webnuxdev.rnde.tm.fr/uwwtd_lu/agglomeration/luaggl12402/2012
WWTP : http://webnuxdev.rnde.tm.fr/uwwtd_lu/treatment-plant/lustep124b001/2012

**Comment by Rakedjian** [comment]
You are right. There is a problem either the agglomerations of Mertert and Womedange are still active and Grevenmacher inactive; either this is the contrary.

I think that this is the second option because Grevenmacher UWWTP has not been finished yet
http://www.sidest.lu/galerie/visite-step-grevenmacher-apsel/


We have the following agglomerations that are declared inactive but not sure that the new UWWTP is operational

- LU_AGGL_124_01 Mertert
- LU_AGGL_129_01 Womeldange
- LU_AGGL_124_02 Grevenmacher

With the following comment in the XML.

A new UWWTP will be build to treat all the waste water issued from the communes of Wasserbillig, Mertert, Grevenmacher, Stadtbredimus, Lenningen and Wormeldange. The new capacity is 47000 p.e.

The agglomeration of Grevenmacher has several sub agglomerations (commune of Wasserbillig, Mertert, Grevenmacher, Stadtbredimus, Lenningen, Manternach and Wormeldange). All these small sub agglomerations have there own collecting system already in place. It is foreseen to connect all these sub agglomerations via a new sewer pipe to a new UWWTP to be build in the agglomeration of Grevenmacher.

and the following UWWTPs that are declared inactive that seems to be correct

- LU_STEP_302_B001 Differdange

The uwwtp of Differdange is closed, the agglomeration of Differdange is connected to the uwwtp of Petange

- LU_STEP_134_B002 Mondorf

The uwwtp of Mondorf is closed, the agglomeration of Mondorf is connected to the new uwwtp of Emerange

- LU_STEP_124_B001 Grevenmacher

A question to raise during the exchange with LU
