### ISSUE TITLE
IE sensitive area

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#268]
Why is the sensitive area declared inactive ?
http://webnuxdev.rnde.tm.fr/uwwtd_ie/receiving-area/iecm_sw_2001_0032/2014

It seems that there are a lot of SA inactive in Ireland

I don't see any reason on that

**Comment by friboben** [comment]
To be checked, probably because field "rcastate" is absent from file for 9th reporting, it was deleted from data model, and the database filling process has a default value put at "0" ie the value meaning inactive in this case. Should be changed with value put at "1", active by default.
Question: how to identify when the SA is inactive, ie which field to use ?

**Comment by Rakedjian** [comment]
I really have to check that.

**Comment by Rakedjian** [comment]
In the SA main table we have begin life and endlife. If there is no endlife before the reporting deadline we have to consider all SA as valide.

**Comment by bbondier** [comment]
The code is already working that way, but the rcaBeginLife is missing in the 9th report for IE.
