### ISSUE TITLE
Bathing water pictogramme

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#301]
You have changed the pictograme when we zoom and the result is that they are not visible anymore. It has to be visible
![bathing water pictogramme](https://cloud.githubusercontent.com/assets/16286544/20134957/a9ae3daa-a66d-11e6-9eaf-abdcbfccd901.GIF)

**Comment by friboben** [comment]
Is due to a change of the base layer by EEA: this is the problem when using external WMS that are beyond our control: any error or change in the way to disseminate is immediately reflected in all end-user platforms. I contacted EEA/ETC early november but did not receive anser: I remind them. (NOTA: similar issue occured for Natura 2000 layer but was settled rapidly)

**Comment by Rakedjian** [comment]
In the EEA mapviewer it is better. It has not changed
http://www.eea.europa.eu/themes/water/interactive/bathing/state-of-bathing-waters

This is this type of icones we need.
