### ISSUE TITLE
CY Difference between connected load to collecting system

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#302]
There is a problem with the calculation of the connected load to collecting system in Cyprus

In summarize compliance and distance to compliance table we have 631 510

![connected load cyprus](https://cloud.githubusercontent.com/assets/16286544/20140444/6e451eaa-a68b-11e6-9891-75a04f2aaeb2.GIF)

But in the statistic menu but also in the installation in place table we have 738 128. This is also the result of the sum of the related column in the agglomeration sheet and the result of the regional analyse.

![connected load cyprus bis](https://cloud.githubusercontent.com/assets/16286544/20140470/a410af72-a68b-11e6-800b-af9940d0748b.GIF)

**Comment by cnassar** [comment]
@Rakedjian can we close this issue ?
The difference is due to the fact that we count only the compliant agglomerations. If an agglomeration has only 50% of the generated load connected to collecting system (and the last part discharged without treatment) the 50% collected is not counted in the table, because the agglomeration is NC.

**Comment by Rakedjian** [comment]
It is ok
