### ISSUE TITLE
2% of load discharged not connected

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#304]
I don't know if there is really a problem but it has to be  checked

The 2% rule of waste water discharge without treatment before connection that lead to a not compliance has not to include the 2%. It means that an agglomeration with exactly 2% is still compliant.

This is what is written in the methodology established by UBA that is available in this folder

https://circabc.europa.eu/w/browse/91312dc0-1690-4d03-ac25-428f83afc541

I have the case of the agglomeration of Plovdiv in Bulgaria where the result is 2.000068%. Due to the decimal it is above 2% that's perhaps why this agglomeration is considered as not compliant. in fact we see in the website and the document 2.0%. 

Could you check that when an agglomeration has exactly 2% it is compliant concerning article 3 and the algorithm are corrects related this rule.

http://webnuxdev.rnde.tm.fr/uwwtd_bg/agglomeration/bgag5678400/2014

**Comment by friboben** [comment]
a) For BG, the perc without treatment is given.
b) In general the algorithms consider the value 2% compliant and only the strict>2% as not compliant, but the above mentioned case 2.000xx% only occurs when the country provides values not rounded (rare) or when the import tool has to calculate because the country has only provided aggC1 and aggC2 (not the case for BG)
c) in the case you mention, it is not the 2% criteria which comes into play but the criteria>2000pe (plovdiv is 11044pe)

**Comment by Rakedjian** [comment]
Ok
