### ISSUE TITLE
calcul of distance to compliance more stringent in Romania

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#367]
When i use the information of the register I don't obtain the numbers that are in the summary table for distance to compliance

 
[distance to compliance more stringent treatment.xlsx](https://github.com/OIEau/uwwtd/files/654867/distance.to.compliance.more.stringent.treatment.xlsx)

**Comment by friboben** [comment]
This is because the table is calculated using the columns CT of table agglomeration level for all agglomerations>10000pe
The line "monitoring results meet requirements for discharge" for more stringent treatment should be completed/corrected to use column CV of table agglomeration level for all agglomerations>10000pe.
