### ISSUE TITLE
Acceptance of article 54

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#373]
Can you confirm that the calculation of not relevant situation  for N and P works for agglomerations above 10 000 pe that discharge in SA even if the 75% removal are not met. 

This is the case for this SA. In fact they can not apply article 54 and they will have to change that in the reporting.

http://webnuxdev.rnde.tm.fr/uwwtd_it/receiving-area/itcm99csaq15001/2015

For this agglomeration that belongs to this SA we have NR for Article 5 compliance but also for the performance

http://webnuxdev.rnde.tm.fr/uwwtd_it/agglomeration/it01000000000101/2015

Why is this situation different from the situation in Paris agglomeration that is also in an article 54 SA area but where the article 5 is considered as compliant

http://webnuxdev.rnde.tm.fr/uwwtd_fr/agglomeration/fr030000175056/2014

It is not clear why there is difference.

**Comment by friboben** [comment]
In the case http://webnuxdev.rnde.tm.fr/uwwtd_it/agglomeration/it01000000000103/2015 we see important information are missing as the timeline is dark grey, we see date format is wrong (mm/dd/yyyy) which should have been corrected by webtool, we see treatment required is secondary as per algorithm 1 http://webnuxdev.rnde.tm.fr/uwwtd_it/treatment-plant/it01000000000001/2015 and we see agglomeration compliance for art5 is NR. However algorithm 9 for 54 is not working well as it should show NC because rate N<75%. Has to be corrected.
For Paris on the contrary it works well as per algo9 it should be C.

**Comment by cnassar** [comment]
already raise with issue 375
