### ISSUE TITLE
Connected but not entering

### ISSUE THREAD

**Issue by Rakedjian** [OIEau/uwwtd#413]
When the load connected and not entering represents more than 1% or sup 2000 Eh,  it means that the Article 4 and Article 5 are not compliant. It seems to be correct in the register

It means also that this load has to be added in the distance to compliance calculation  for Article 4 and article 5. 

In the last version of the calculation has it be included?

In the previous version for France it has not been integrated for article 4 and 5. 

If Article 54 applies it does not apply for BOD and COD performance that are included in the article 5 performance

![connected but not treated](https://cloud.githubusercontent.com/assets/16286544/22425003/61c4eed6-e6f9-11e6-9e63-9fa0bc8789bf.GIF)

**Comment by cnassar** [comment]
It is now included in both equipement and performance distance to compliance, for Article 4 and Article 5.
However, I need your confirmation about the last sentence : "If Article 54 applies it does not apply for BOD and COD performance that are included in the article 5 performance".
Do you mean that the leak must not be taken into consideration in the distance to compliance when article 5(4) applies ?
In any case, because of the leak, the article 4 will be not compliant and so will be article 5 (because of hierachical compliance). However, I need more precision on what must we put in the distance to compliance.

**Comment by Rakedjian** [comment]
When there is an issue with BOD and COD it is to be included in the distance to compliance performance article 5 even if article 54 applies

It is also not compliant article 5 without hierarchical approach

**Comment by cnassar** [comment]
fixed

**Comment by cnassar** [comment]
however need to generate the register againe.
@Rakedjian I will keep you informed when it will be done.
