### ISSUE TITLE
Compliance on Treatment type Other

### ISSUE THREAD

**Issue by ndhuygelaere** [OIEau/uwwtd#466]
In this case, the required treatement is secondary and non require treatment in place (chlrorination) is fail, but it should be not disqualifying on compliance.
Need check 
https://dev.oieau.fr/uwwtd_it/treatment-plant/it19sr00g0013de002/2014

**Comment by friboben** [comment]
2 elements: - in 2014 2 agglomerations connected to the TP (see https://dev.oieau.fr/uwwtd_it/agglomeration/it198901301/2014) while in 2016 only one.
- the treatment plant https://dev.oieau.fr/uwwtd_it/agglomeration/it198901303/2014 in graphical network summary should have a colour (red or green but not black, check with rules but I guess red because secondary equipement is not provided, even if performance is at pass and required is secondary)
